NEST-338: Re-implement Azure Reset build with GitHub Actions
Lombiq/Infrastructure-Scripts pull request #1
Opened 2022-11-03 19:41 UTC by DemeSzabolcs

NEST-338

2022-11-05 22:22 UTC, Piedone requested changes

2022-11-06 03:13 UTC, DemeSzabolcs commented on PowerShell/Utilities/Test-Url/Test-Url.psm1
> +<#
This file is already in `dev` I needed this.

2022-11-06 18:39 UTC, Piedone requested changes

2022-11-06 18:39 UTC, Piedone commented on .github/actions/initialize/action.yml
> +        }
```suggestion
        {
            Import-Module $moduleName.Name
        }
```

2022-11-07 14:29 UTC, Piedone approved these changes

2022-11-07 15:05 UTC, Piedone commented
@BenedekFarkas do we still need the feature branch?

2022-11-07 15:07 UTC, merged

2022-11-07 17:30 UTC, Piedone commented
Great then!