OSOE-482: Enforce parameter splatting instead of backtick in Lombiq.Analyzers.PowerShell
Lombiq/Infrastructure-Scripts pull request #10
Opened 2022-11-25 15:12 UTC by BenedekFarkas

OSOE-482

2022-11-29 18:12 UTC, Piedone requested changes
I'd prefer not to do this tab stop-alignment here either.

2022-12-18 18:20 UTC, BenedekFarkas commented
> I'd prefer not to do this tab stop-alignment here either.

Agreed, for reference, I replied on another PR: https://github.com/Lombiq/Utility-Scripts/pull/28#discussion_r1051637023

2022-12-19 21:46 UTC, Piedone requested changes

2022-12-19 21:46 UTC, Piedone commented on PowerShell/Azure/Sql/Get-AzureWebAppSqlDatabase/Get-AzureWebAppSqlDatabase.psm1
> +    }
```suggestion
    }
```

2022-12-19 21:46 UTC, Piedone commented on .github/workflows/static-code-analysis.yml
> -defaults:
See my notes about the workflow here: https://github.com/Lombiq/Utility-Scripts/pull/28#discussion_r1052640912

2022-12-20 09:19 UTC, BenedekFarkas commented on PowerShell/Azure/Sql/Get-AzureWebAppSqlDatabase/Get-AzureWebAppSqlDatabase.psm1
> +    }
Not sure how these can creep back in sometimes, but it's really annoying that removing trailing whitespaces is not a default step of code cleanup (Ctrl+K+D with the keymap imported from VS). VS Code can do it too with Ctrl+K+X, but you can't bind multiple commands to the same key combination without an extension.
I updated my Razer Synapse macro to run it too before Ctrl+K+D and Ctrl+R+G (usings cleanup).

2022-12-20 15:36 UTC, Piedone approved these changes

2022-12-20 17:41 UTC, merged