INFRA-124: PowerShell Analyzers integration
Lombiq/Infrastructure-Scripts pull request #5
Opened 2022-11-16 11:35 UTC by BenedekFarkas

INFRA-124

2022-11-17 16:19 UTC, DAud-IcI requested changes

2022-11-17 16:19 UTC, sarahelsaig commented on PowerShell/Azure/Profile/Connect-AzServicePrincipal/Connect-AzServicePrincipal.psm1
> +        [Parameter(Mandatory = $true, HelpMessage = "Please provide the thumbprint of the certificate to authenticate with!")]
I don't think the `Please provide` is needed here, a help text should be descriptive (like it is [here](https://github.com/Lombiq/Infrastructure-Scripts/pull/5/files#diff-3d2fb43ce138c3d1e12da8bf41c02bded233f8e649ec5c4762eccf75d04c1869L34))

2022-11-17 16:19 UTC, sarahelsaig commented on PowerShell/Azure/Sql/Invoke-AzureWebAppSqlDatabaseExport/Invoke-AzureWebAppSqlDatabaseExport.psm1
> +        Write-Output ("`n*****`nDatabase export starting...`n*****")
Why do all the Write cmdlets have parentheses? Seems unnecessary.

2022-11-17 16:19 UTC, sarahelsaig commented on PowerShell/Azure/Storage/Invoke-AzureWebAppStorageContainerCopy/Invoke-AzureWebAppStorageContainerCopy.psm1
> +                        -Name $DestinationContainerName -ErrorAction Stop
Instead of delimiting line breaks with a backtick, use splatting. ([see wiki](https://lombiq.atlassian.net/wiki/spaces/DEV/pages/43384918/PowerShell+code+conventions?focusedCommentId=2613936294))

2022-11-18 10:19 UTC, BenedekFarkas commented
@DAud-IcI I agree with all your feedback and these exact things bother me a bit as well (made some changes along the same lines in a few places in this PR), but I was focusing on just fixing the violations to get the analyzer integration out the door. I'd rather move these code quality/cleanliness changes to a new issue/PR.

2022-11-18 17:10 UTC, merged